name:                derive-topdown
version:             0.1.0.0
github:              "HaskellZhangSong/derive-topdown"
license:             BSD3
author:              "Song Zhang"
maintainer:          "Song Zhang <Haskell.Zhang.Song@hotmail.com>"
copyright:           "(c) 2024 Song Zhang"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Derive type class instances
category:            Development

description: This package will make it easier to derive class instance for complex composited data types by using Template Haskell.        

tested-with:   GHC == 8.2.2
             , GHC == 8.4.4
             , GHC == 8.6.5
             , GHC == 8.8.4
             , GHC == 8.10.7
             , GHC == 9.0.2
             , GHC == 9.2.8
             , GHC == 9.4.8
             , GHC == 9.6.5
             , GHC == 9.8.2
             , GHC == 9.10.1

dependencies:
- base >= 4.8 && < 5
- template-haskell
- syb
- primitive
- th-expand-syns
- mtl
- transformers
- containers
- th-abstraction
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wpartial-fields
- -Wmissing-home-modules
- -Wmissing-export-lists

library:
  source-dirs: src
  default-extensions: 
     TemplateHaskell
   , StandaloneDeriving
   , CPP
  exposed-modules:
  - Data.Derive.Superclass
  - Data.Derive.TopDown.Breaks
  - Data.Derive.TopDown.IsInstance
  - Data.Derive.TopDown.Instance
  - Data.Derive.TopDown.CxtGen
  - Data.Derive.TopDown.Standalone
  - Data.Derive.TopDown.TH
  - Data.Derive.TopDown.Types
  - Data.Derive.TopDown
  other-modules:
  - Data.Derive.TopDown.Lib

tests:
  derive-topdown-test:
    main:                Spec.hs
    source-dirs:         test
    when:
    - condition: impl(ghc >= 8.6.1)
      then:
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -Wno-missing-signatures
        - -Wno-unticked-promoted-constructors
        - -Wno-orphans
        - -Wno-missing-export-lists
        - -Wno-star-is-type
      else:
        ghc-options:
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
        - -Wno-missing-signatures
        - -Wno-unticked-promoted-constructors
        - -Wno-orphans
        - -Wno-missing-export-lists

    dependencies:
    - derive-topdown
    - HUnit
    - haskell-src
    - binary
    - ghc
    - bytestring